config/routes.rb
Rails.application.routes.draw do
 
 
  resources :hoges
  ActiveAdmin.routes(self)
 #####################   home   #####################
 
  get "/" => "home#top"
  get "/about" => "home#about"
  
 #####################   posts   #####################
   
  get  "posts/index" => "posts#index"
  get  "/posts/new" => "posts#new"
 # get  "posts/:id/edit" => "posts#edit"
  get  "posts/search" => "posts#index"
  #get  "/posts/:id"=> "posts#show"
 
 # post "/posts/create" => "posts#create"
  #post "/posts/:id/update"=> "posts#update"
  post "/posts/:id/destroy"=> "posts#destroy"
 resources :posts
 #####################   users   #####################
 
   get "users/index" => "users#index"
  get "users/:id/likes" => "users#likes"
  #get "users/:id/edit" => "users#edit"
  #get "users/:id" => "users#show"
  
  #patch "users/:id/update" => "users#update"
  post "users/create" => "users#create"
   post "/users/:id/destroy"=> "users#destroy"
   resources :users
   resources :tags
  

 #####################   users   #####################

  post "likes/:post_id/create" => "likes#create"  
  post "likes/:post_id/destroy" => "likes#destroy"
  post "login" => "users#login"
  post "logout" => "users#logout"
  
  get "signup"=> "users#new"                   ##ユーザー登録ページ
  get  "login"=> "users#login_form"
 
 ##################### follow    #########################
 
  post  "users/:id/follow" =>   "users#follow"
  post  "users/:id/unfollow" =>   "users#unfollow"

######################### return ########################
resources :returns
post "/returns/:id/destroy"=> "returns#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
   mount_uploader :img, ImgUploader

  has_secure_password
  acts_as_followable # フォロワー機能
  acts_as_follower   # フォロー機能
  attr_accessor :image
  has_many :posts,dependent: :destroy
  has_many :returns,dependent: :destroy
  has_many :likes, dependent: :destroy
  acts_as_tagger
  acts_as_taggable # acts_as_taggable_on :tags のエイリアス
  acts_as_taggable_on :labels # post.label_list が追加される
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :name,presence: true, length: { maximum: 8 }               #  存在性
  validates :profile,length: { maximum: 80 } 

  def posts
    return  Post.where(user_id: self.id)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit,:update,:destroy]}
  
  def index
    @users = User.paginate(:page => params[:page], :per_page => 6)
  end
  
  def show
    @users = User.find(params[:id])
    @posts = Post.find_by(user_id: params[:id])
    @postall =Post.where(user_id: @users.id)
    @returns = Return.all
    if @posts !=nil
      @likes_count = Like.where(post_id: @posts.id).count
    end
  end
 
  def new
    @users = User.new
  end 
  
  def create        
    #raise.params.inspect
    @users =User.new(user_params)
    if @users.save
      session[:user_id]=@users.id
      flash[:notice]="ユーザー登録を完了しました"
      redirect_to users_path(@users) 
    else
      render "users/new"
    end  
  end  
   
  def login_form
  end
   
  def login
    @users = User.find_by(email: params[:session][:email].downcase)
    if @users && @users.authenticate(params[:session][:password])
      session[:user_id]=@users.id
      flash[:notice]="ログイン成功しました"
      redirect_to("/users/index")
    else
      @error_message ="E-mail address or password is wrong"
      render("users/login_form") 
    end 
  end 
   
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end
    
  def update
     #raise.params.inspect
    @users = User.find_by(id: params[:id])
    if  @users.update_attributes(user_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@users.id}")
    else
      render("users/edit")  
    end
  end
 
  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to ("/login")
  end
 
  def likes 
    @users = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end
    
  def edit
    @users = User.find_by(id: params[:id])
  end
    
  def ensure_correct_user
    @users=User.find_by(id: params[:id])
    if @users.id !=@current_user.id
      flash[:notice]="権限がありません"
      redirect_to("/posts/index")
    end
  end 
 
  def follow
    @users = User.find_by(id: params[:id])
    #ログイン中のユーザーで対象のユーザー(@user)をフォローする
    @current_user.follow(@users)
    redirect_to("/users/#{@users.id}")
    flash[:notice] = "#{@users.name}さんフォローしました"
  end

  def unfollow
    @users = User.find_by(id: params[:id])
    #ログイン中のユーザーで対象のユーザー(@user)をフォロー解除する
    @current_user.stop_following(@users)
    redirect_to("/users/#{@users.id}")
    flash[:notice] = "#{@users.name}さんをフォローを解除しました"
  end
  
  def tag_list
   # order('count DESC')でカウントの多い順にタグを並べています
    @tags = User.tag_counts_on(:tags).order('count DESC')
  end
  
  def tag_list
  end
  
  private
  
  def user_params
      params.require(:user).permit(
      :name, :email, :password, 
      :password_confirmation,:img,:image_cache,:remove_img,:tag_list,:profile)
  end
end
 

app/helpers/users_helper.rb
module UsersHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/users/_follow.html.erb
<% if @users.id != @current_user.id %>
  <li class="collection-item">
    <% unless @current_user.following?(@users) %>
      <div class="action">
         <%= link_to 'Follow' ,"/users/#{@users.id}/follow",method: :post, class: "button1" ,remote: true %>
      </div>
     <% else %>
      <div class="action">
          <%= link_to 'Unfollow' ,"/users/#{@users.id}/unfollow", method: :post,class: "button1",remote: true %>
      </div>
    <% end %>
  </li>
<% end %>

app/views/users/_followd.html.erb
<div class="follow-container">
  <% @users.followers.each do |f|%>
    <div class="user-profile">
      <div class="user-list-image">
      <%= image_tag f.img.url,:class => "user-image" %>
      <%if @current_user.following? (f)%>
        <div class="back-message">フォローしています
        </div>
      <%end%>
      </div>
        <div class="prof"> 
          <%=link_to(f.name,"/users/#{f.id}",class:"show-index")%>
        </div>
          <div class="user-profile-page">
            <div class="show-profile"> <%=f.profile%>
            </div>
         </div> 
    </div>
  <%end%>
</div>

app/views/users/_follows.html.erb
<div class="follow-container">
  <% @users.all_following.each do |f|%>
    <div class="user-profile">
      <div class="user-list-image">
        <%= image_tag f.img.url,:class => "user-image" %>
        <%if @current_user.followed_by? (f)%>
          <div class="back-message">フォローされています</div>
        <%end%>
      </div>
        <div class="prof">
          <%=link_to(f.name,"/users/#{f.id}",class:"show-index")%>
        </div>
          <div class="user-profile-page">
            <div class="show-profile"> <%=f.profile%></div>
          </div> 
    </div>
  <%end%>
</div>

app/views/users/_followsPeople.html.erb
<div class="follow-container">
 <p>フォローしています</p>

  <% @users.all_following.each do |f|%>
 <div class="user-box">
    <%= f.name%>
  
    <img src="<%= "/user_images/#{f.image_name}" %>">
 
    <%if @current_user.followed_by? (f)%>
     フォローされています
     <%end%>
 </div>
    <%end%>
    
</div>

app/views/users/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="label label-primary"><%= tag %></span>
<% end %>

app/views/users/_tweet.html.erb
<div class="post-index-back">
  <% @users.posts.reverse_each do |post|%>  <!--modelのpostsメソッド-->
    <div class="post-index-cover-user">
      <div class="post-main-users">
        <div class="post-main-box">
          <div class="post-index-img">
            <%= image_tag post.user.img.url,:class => "user-image" %>
          </div>
            <div class="post-index-inner">
              <div class="post-main-detail">
                <%= "#{post.user.name}"+'  ' %>
                <%= "#{post.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[post.created_at.wday]})") }" %><br>
              </div>
              <p class="post-index-content"><%==simple_format(post.content) %></p>
                <% if post.postimage.present? %>
      <!--画像--><%= image_tag post.postimage.url,:class => "post-image"%>
                <%end%>
                  <div class="post-index-action">
                    <ul class="ultag">
         <!--いいね--><% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>
                        <%= link_to("/likes/#{post.id}/destroy",{method: "post",class:"tagf like-btn-unlike faa-pulse animated-hover"}, remote: true) do %>
                          <li><p class="itext"> <i class="fas fa-heart "></i></p></li>
                        <%end%>
                      <%else%>
                      <%= link_to("/likes/#{post.id}/create", {method: "post",class:"tagf like-btn faa-pulse animated-hover"},:select_id => "a") do %>
                        <li><p class="itext"> <i class="far fa-heart "></i></p></li>
                      <%end%>
                    <%end%>
                      <div class="tagf">   <li><p class="itext">     <%= post.like_count %>   </li></p> </div>  
                        <%=link_to(new_return_path(p_id: post.id),class:"tagf")do%>
                          <li> <p class="itext">  <i class="fas fa-reply"></i>返信</p></li>
                        <%end%>
                          <%if post.user_id==@current_user.id%>
                            <%=link_to("/posts/#{post.id}/edit",class:"tagf")do%>
                              <li><p class="itext">    <i class="fas fa-edit"></i>編集</p></li>
                          <%end%>
                          <%=link_to("/posts/#{post.id}/destroy",method: "post",data: {confirm: "本当に削除しますか？"},class:" tagf" ) do%>
                            <li><p class="itext"><i class="far fa-trash-alt"></i>削除</p></li>  
                          <%end%>
                       <%end%>
                       <%- post.tags.each do |tag| %> <!--タグサ--->
                         <li><%=link_to posts_index_path(:tagsearch =>  tag.name).gsub("+", "%20") do%>
                           <p class="itext"> <i class="fas fa-leaf"></i> <%=tag.name%> </p></li>
                         <% end %> 
                       <% end %>
                     </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
 

app/views/users/edit.html.erb
<div class="new-main">
  <div class="resister-area">
    <div class="inner-area">
      <h1>アカウント編集</h1>
        <% @users.errors.full_messages.each do |message| %>
         <p class="errors">
           <%= message %>
         </p>
        <% end %>
          <%= form_for @users ,url: user_path,class:"edit-image"  do |f| %>
            <p class="standard-font">ユーザー名</p>
            <%= f.text_field :name %><br>
            
            <p class="standard-font">メールアドレス</p>
            <%= f.email_field :email %><br>
              <div class="field"><br>
                <div class ="before-user-image">
                  <%= image_tag @users.img.url, id: :img_prev if @users.img? %><br>
                </div>
                  <%= f.check_box :remove_img %>画像を削除する<br><br>
                  <%= f.file_field :img, id: :users_img %><br><br>
<script type="text/javascript">
$(function() {
 function readURL(input) {
   if (input.files && input.files[0]) {
     var reader = new FileReader();
     reader.onload = function (e) {
       $('#img_prev').attr('src', e.target.result);
     }
     reader.readAsDataURL(input.files[0]);
   }
 }
 $("#users_img").change(function(){
   readURL(this);
 });
});
</script>
              </div>
  <p class="standard-font">プロフィール</p>
    <%= f.text_area :profile ,class: "text-edit-area",placeholder:"プロフィール(80文字以内)"%><br><br>
    <%= f.submit "保存", class: "button1" %><br>
    <% end %>
    </div>
  </div>
</div>

app/views/users/form.html.erb
<%= form_for(@users) do |f| %>
  <div class="field">
    <%= f.label :interest_list, "興味・関心（カンマ区切り）" %><br>
    <%= text_field_tag 'user[interest_list]', @users.interest_list.join(',') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="user-list-cover">
  <div class="user-list">
    <%= will_paginate %>
      <% @users.each do |user| %>
        <div class="user-profile">
          <div class="user-list-image">
            <%= image_tag user.img.url,:class => "user-image" %>
          </div>
          <div class="prof">
            <%=link_to(user.name,"/users/#{user.id}",class:"show-index")%>
          </div>
          <div class="user-profile-page">
            <div class="show-profile"> <%=user.profile%>
            </div>
          </div> 
        </div>
       <% end %>
    <%= will_paginate %>
  </div>
</div>
 
 

app/views/users/likes.html.erb
<h2><%= @user.name %></h2>
  <p><%= @user.email %></p>
    <% if @user.id == @current_user.id %>
      <%= link_to("編集", "/users/#{@user.id}/edit") %>
    <% end %>
      <ul class="user-tabs">
        <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
        <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
      </ul>
        <%<% @likes.each do |like| %>%>
        <% post = Post.find_by(id: like.post_id) %>
          <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        <%end %>

app/views/users/login_form.html.erb
<div class="new-main">
  <div class="resister-area">
    <div class="sampleuser"><br>
      <p>こちらをご利用ください</p>
      <p>email:sample@yahoo.com</p>
      <p>password:11111111</p>
      <br>
    </div>
    <div class="inner-area">
      <p font-size="20px">ログイン</p>
      <% if @error_message%>
        <p class="errors"><%= @error_message %></p>
      <% end %>
      <%= form_for :session, url: login_path do |f| %>
        <div class="input-area">
         メールアドレス<br>
        <%= f.text_field :email %><br />
         パスワード<br>
        <%= f.password_field :password%><br/><br/>
        <%= f.submit "ログイン",:class =>"button1" %><br/>
      <%end%>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="new-main">
  <div class="resister-area">
    <div class="inner-area">
      <p>新規ユーザー登録</p>
        <%@users.errors.full_messages.each do |message|%>
          <p class="errors"><%=message%></p>
        <%end%>
          <div class="input-area">
            <%= form_for @users, url: "/users/create" do |f| %>
          ユーザー名<br>
          <%= f.text_field :name %><br/>
          メールアドレス<br>
          <%= f.text_field :email %><br />
          パスワード<br>
          <%= f.password_field :password %><br />
          パスワード確認<br>
          <%= f.password_field :password_confirmation%><br/>
           サムネイル画像<br/>
          <%= f.file_field :img %><br/><br/>
          <%= f.submit "新規登録",:class =>"button1" %><br/>
          </div>
            <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="prof-show-container">
  <div class="prof-show-detail">
    <div class="show-image">
      <% if  @users.img.present? %>
        <%= image_tag @users.img.url,:class => "user-image" %>
      <% end%>
      <%if @current_user==@users%>
      <%elsif @current_user.following? @users%>  <!--もしフォろーしてたら-->
        <div class="back-message"> <%=@users.name%>をフォローしています</div>
      <%end%>
    </div>
      <div class="show-users-identfy">
        <div class="user-name"><%= "#{@users.name}" %>
        </div>
      </div>
        <div class="user-show-profile"> <%=@users.profile%></div>
          <div class="follow-info">
            <ul  class="show-menus">
              <li>
                <%=link_to("/users/#{@users.id}/edit",class:"tagf")do%>
                <p class="itext">    <i class="fas fa-edit"></i>アカウント編集 </p>
                <%end%>
              </li>
              <li>
                <%=link_to("/users/#{@users.id}/destroy",method: "post",data: {confirm: "本当に削除しますか？"},class:" tagf" ) do%>
                <p class="itext"><i class="far fa-trash-alt"></i>削除</p>
                <%end%>
              </li>
              <li>フォロー</li>
              <li><%=@users.follow_count%>人</li>
              <li>フォロワー </li>
              <li><%=@users.followers_count%>人</li>
                <%=render"users/follow"%>     <!--followのパーシャル-->
              <li><span class="fa fa-heart like-btn-unlike"></span>
              </li>
              <li><%=Like.where(post_id: @users.id,post_id: @postall).count%>
              
                 
              </li> 
            </ul>
          </div>
        </div>
        <div class="main-container">   <!--main-->
          <div class="mc-list">         <!--↓-->
            <div class="tabs">
              <input id="all" type="radio" name="tab_item" checked>
              <label class="tab_item" for="all">
              <p class="itext">     <i class="far fa-comment"></i> つぶやき </p></label>
              <input id="programming" type="radio" name="tab_item">
              <label class="tab_item" for="programming">
              <p class="itext">     <i class="fas fa-users"></i> フォロー </p></label>
              <input id="design" type="radio" name="tab_item">
              <label class="tab_item" for="design">
               <p class="itext">     <i class="fas fa-users"></i> フォロワー </p></label>
              <div class="tab_content" id="all_content">
                <div class="tab_content_description">
                  <p class="c-txtsp"><%=render"users/tweet"%></p>
                </div>
              </div>
                <div class="tab_content" id="programming_content">
                  <div class="tab_content_description">
                    <p class="c-txtsp"><%=render"users/follows"%></p>
                  </div>
                </div>  
              <div class="tab_content" id="design_content">
                <div class="tab_content_description">
                  <p class="c-txtsp"> <%=render"users/followd"%></p>
                </div>
              </div>
      </div> 
    </div>
  </div>
</div>
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      