config/routes.rb
Rails.application.routes.draw do
 
 
  resources :hoges
  ActiveAdmin.routes(self)
 #####################   home   #####################
 
  get "/" => "home#top"
  get "/about" => "home#about"
  
 #####################   posts   #####################
   
  get  "posts/index" => "posts#index"
  get  "/posts/new" => "posts#new"
 # get  "posts/:id/edit" => "posts#edit"
  get  "posts/search" => "posts#index"
  #get  "/posts/:id"=> "posts#show"
 
 # post "/posts/create" => "posts#create"
  #post "/posts/:id/update"=> "posts#update"
  post "/posts/:id/destroy"=> "posts#destroy"
 resources :posts
 #####################   users   #####################
 
   get "users/index" => "users#index"
  get "users/:id/likes" => "users#likes"
  #get "users/:id/edit" => "users#edit"
  #get "users/:id" => "users#show"
  
  #patch "users/:id/update" => "users#update"
  post "users/create" => "users#create"
   post "/users/:id/destroy"=> "users#destroy"
   resources :users
   resources :tags
  

 #####################   users   #####################

  post "likes/:post_id/create" => "likes#create"  
  post "likes/:post_id/destroy" => "likes#destroy"
  post "login" => "users#login"
  post "logout" => "users#logout"
  
  get "signup"=> "users#new"                   ##ユーザー登録ページ
  get  "login"=> "users#login_form"
 
 ##################### follow    #########################
 
  post  "users/:id/follow" =>   "users#follow"
  post  "users/:id/unfollow" =>   "users#unfollow"

######################### return ########################
resources :returns
post "/returns/:id/destroy"=> "returns#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/return.rb
class Return < ApplicationRecord
  validates :returncontent,{presence: true,length:{maximum: 8}}
  belongs_to :post
  belongs_to :user

  def user
    return  User.find_by(id: self.user_id)
  end
  
  def posts
    return  Post.find_by(user_id: self.id)
  end  
  
  def like_count
    return   Like.where(post_id: self.id).count
  end

  def self.search(search)
    if search
      Post.where(['content LIKE ?', "%#{search}%"])
    else
      Post.all
    end
  end
end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
  
   before_action :ensure_correct_user,{only:[:edit,:update,:destroy]}
 
 def show
   @returns = Return.find_by(id: params[:id])
 end
 
 def new
   @returns=Return.new
 end
  
 def edit
   @returns=Return.find_by(id: params[:id])
 end
  
 def update
   @returns=Return.find_by(id: params[:id])
   if  @returns.update_attributes(return_params)
     flash[:notice]="投稿を編集しました"
     redirect_to("/posts/index")
   else
     render("returns/edit")   
   end
 end

 def destroy
   @returns=Return.find_by(id: params[:id]) 
   @returns.destroy
   redirect_to("/posts/index")
   flash[:notice]="投稿を削除しました"
 end 

  #コメント追加アクション
 def create
   @returns = Return.create(return_params)
   #raise.params.inspect
   redirect_to ("/posts/index")
 end
 
 def ensure_correct_user
   @returns=Return.find_by(id: params[:id])
   if @returns.user_id !=@current_user.id
     flash[:notice]="権限がありません"
     redirect_to("/posts/index")
   end
 end
  
  private
  #ストロングパラメータ

  def return_params
    return_params = params.require(:return).permit(:returncontent,:returnimage,:post_id)
    .merge(user_id: @current_user.id)
  end
end

app/views/returns/_show.html.1.erb
<br>
<br>
<br>
<br>
<br>
<br>
id<%=@returns.id%><br>
コメ<%=@returns.returncontent%><br>
ユーザー<%=@returns.user_id%><br>
被投稿<%=@returns.post_id%><br>
<% if Like.find_by(user_id: @current_user.id,post_id: @returns.id)%>
    <%= link_to("/likes/#{@returns.id}/destroy",{method: "post"},class:"post-detail") do %>
    <span class="fa fa-heart like-btn-unlike"></span>
  <%end%>
  <%else%>
    <%= link_to("/likes/#{@returns.id}/create", {method: "post"},class:"post-detail",:select_id => "a") do %>
      <span class="fa fa-heart like-btn"></span>
   <%end%>
 <%end%>
 <%= @returns.like_count %>   

app/views/returns/edit.html.erb
<div class="new-main">
  <div class="resister-area">
    <div class="inner-area">
      <%= form_for @returns ,url: return_path,class:"edit-image"  do |f| %>
      <p font-size="20px">編集する</p>
      <%@returns.errors.full_messages.each do |message|%>
        <div class="errors"><%=message%></div>
      <%end%>
      <div class="input-area">  
        <%= f.text_field :returncontent ,placeholder: @returns.returncontent %><br><br>
        <%=f.submit value:"投稿", class:"button1"%>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/returns/new.html.erb
<div class="new-main">
 <div class="resister-area">
   <div class="inner-area">
     <p font-size="20px">一言コメント</p>
     <%= form_for @returns,  url: returns_path do |f| %> 
       <%= f.text_field :returncontent ,placeholder:"8文字以内"%> 
       <%= f.hidden_field :post_id, value: params[:p_id] %>
       <br><br>
     <%=f.submit value:"投稿", class:"button1"%>
     <%end%>
    </div>
  </div>
</div>

app/views/returns/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
id<%=@returns.id%><br>
コメ<%=@returns.returncontent%><br>
ユーザー<%=@returns.user_id%><br>
被投稿<%=@returns.post_id%><br>
<% if Like.find_by(user_id: @current_user.id,post_id: @returns.id)%>
    <%= link_to("/likes/#{@returns.id}/destroy",{method: "post"},class:"post-detail") do %>
    <span class="fa fa-heart like-btn-unlike"></span>
  <%end%>
  <%else%>
    <%= link_to("/likes/#{@returns.id}/create", {method: "post"},class:"post-detail",:select_id => "a") do %>
      <span class="fa fa-heart like-btn"></span>
   <%end%>
 <%end%>
 <%= @returns.like_count %>   