config/routes.rb
Rails.application.routes.draw do
 
 
  resources :hoges
  ActiveAdmin.routes(self)
 #####################   home   #####################
 
  get "/" => "home#top"
  get "/about" => "home#about"
  
 #####################   posts   #####################
   
  get  "posts/index" => "posts#index"
  get  "/posts/new" => "posts#new"
 # get  "posts/:id/edit" => "posts#edit"
  get  "posts/search" => "posts#index"
  #get  "/posts/:id"=> "posts#show"
 
 # post "/posts/create" => "posts#create"
  #post "/posts/:id/update"=> "posts#update"
  post "/posts/:id/destroy"=> "posts#destroy"
 resources :posts
 #####################   users   #####################
 
   get "users/index" => "users#index"
  get "users/:id/likes" => "users#likes"
  #get "users/:id/edit" => "users#edit"
  #get "users/:id" => "users#show"
  
  #patch "users/:id/update" => "users#update"
  post "users/create" => "users#create"
   post "/users/:id/destroy"=> "users#destroy"
   resources :users
   resources :tags
  

 #####################   users   #####################

  post "likes/:post_id/create" => "likes#create"  
  post "likes/:post_id/destroy" => "likes#destroy"
  post "login" => "users#login"
  post "logout" => "users#logout"
  
  get "signup"=> "users#new"                   ##ユーザー登録ページ
  get  "login"=> "users#login_form"
 
 ##################### follow    #########################
 
  post  "users/:id/follow" =>   "users#follow"
  post  "users/:id/unfollow" =>   "users#unfollow"

######################### return ########################
resources :returns
post "/returns/:id/destroy"=> "returns#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content,{presence: true,length:{maximum: 140}}
  validates :user_id,{presence: true}
  mount_uploader :postimage, PostimageUploader
  belongs_to :user
  has_many :returns,dependent: :destroy
  has_many :likes, dependent: :destroy

  acts_as_taggable_on :labels,:tag_list # post.label_list が追加される
  acts_as_taggable            
  acts_as_taggable_on :interests  
    
  def user
    return  User.find_by(id: self.user_id)
  end
  
  def returns
    return Return.find_by(post_id: self.id)
  end
  
  def like_count
    return   Like.where(post_id: self.id).count
  end

  def self.search(search)
    if search
     Post.where(['content LIKE ?', "%#{search}%"])
         # raise.params.inspect
    else
      Post.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :ensure_correct_user,{only:[:edit,:update,:destroy]}
  before_action :authenticate_user
 
  def index
     
    if  params[:id].present?
        @posts = Post.find_by(id: params[:id])
    else
      @post=Post.new
    end
    
    @returns = Return.all
    @tags = ActsAsTaggableOn::Tag.most_used
  
    if params[:tagsearch]
     @posts =Post.tagged_with( params[:tagsearch])
     params[:tagsearch]=nil
    else
     @posts = Post.search(params[:search]).order(created_at: :desc) 
     params[:search]=nil
    end 
  end  

  def show
    @posts =Post.find_by(id: params[:id])
    @users = User.find_by(id: @posts.user_id)
    @user = @posts.user
    @likes_count = Like.where(post_id: @posts.id).count
  end
  
  def new
    @posts=Post.new
  end  
  
  def create
    @posts =Post.new(post_params)
    if @posts.save
       redirect_to("/posts/index")
       flash[:notice]="投稿を作成しました"
    else 
       render("posts/new")   
    end
  end
  
  def edit
    @posts=Post.find_by(id: params[:id])
  end
  
  def update
    @posts=Post.find_by(id: params[:id])
    if  @posts.update_attributes(post_params)
   # raise.params.inspect
      flash[:notice]="投稿を編集しました"
      redirect_to("/posts/index")
    else
      render("posts/edit")   
    end
  end
  
  def destroy
    @posts=Post.find_by(id: params[:id]) 
    if @posts.destroy
      @posts.tag_list.remove(@posts.all_tags_list)
      redirect_to("/posts/index")
      flash[:notice]="投稿を削除しました"
    end
  end 
  
  def ensure_correct_user
    @posts=Post.find_by(id: params[:id])
    if @posts.user_id !=@current_user.id
      flash[:notice]="権限がありません"
      redirect_to("/posts/index")
    end
  end
  
  private
 
  def post_params
      params.require(:post).permit(
      :content, :user_id, :postimage,:remove_postimage,:interests,:tag_list)
      .merge(user_id: @current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
 <div class="post-index-action">
                     <% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>
                       <%= link_to("/likes/#{post.id}/destroy",{method: "post"},class:"post-detail", remote: true) do %>
         <!--いいね--> <span class="fa fa-heart like-btn-unlike fbut action_height"></i></span>
                     <%end%>
                     <%else%>
                       <%= link_to("/likes/#{post.id}/create", {method: "post"},class:"post-detail",:select_id => "a", remote: true) do %>
                         <span class="fa fa-heart like-btn fbut action_height"></span>
                      <%end%>
                    <%end%>

app/views/posts/_search.html.erb
<p>検索</p>
<%= form_tag("/posts/search",:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<%if @posts.present?%>
<ul><% @posts.each do |post| %>
  <li>
    
    <%= post.created_at %>
    <%= post.content %>
  </li>
 
  <% end %>
   <% end %>
</ul>

app/views/posts/_tweet.html.erb
$("#like-buttons").html("<%= j(render partial: 'like-show', locals: {like: @like }) %>");

app/views/posts/edit.html.erb
<div class="new-main">
  <div class="resister-area">
    <div class="inner-area">
      <%= form_for @posts ,url: post_path,class:"edit-image"  do |f| %>
         <p font-size="20px">編集する</p>
         <%@posts.errors.full_messages.each do |message|%>
         <p class="errors"><%=message%></p>
      <%end%>
        <textarea name="content" class="text-area"><%=@posts.content%></textarea><br><br>
        <%= image_tag @posts.postimage.url, id: :img_prev if @posts.postimage? %><br>
    </div>
      <%= f.check_box :remove_postimage %>画像を削除する<br><br>
      <%= f.file_field :postimage, id: :post %><br><br>
    <script type="text/javascript">
$(function() {
 function readURL(input) {
   if (input.files && input.files[0]) {
     var reader = new FileReader();
     reader.onload = function (e) {
       $('#img_prev').attr('src', e.target.result);
     }
     reader.readAsDataURL(input.files[0]);
   }
 }
 $("#users_img").change(function(){
   readURL(this);
 });
});
</script>        
             <%= text_field_tag 'post[tag_list]', @posts.tag_list.join(',') %><br><br>
             <input type="submit" value="投稿" class="button1"></input>
      <%end%>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main">
  <div class="index-container-cover">
    <div class="index-container">
     <!-----------tag search box------------>
      <div class="tag-serch-main">
        <div class="tag">
          <ul class="ultag">
            <p font-size="10px">人気タグ</p>
            <%- @tags.each do |tag| %> <!--タグサ--->
            <li><%=link_to (posts_index_path(:tagsearch =>  tag.name).gsub("+", "%20")) do%>
              <p class="itext"> <i class="fas fa-leaf"></i> <%=tag.name%> </p></li>
                <% end %> 
            <% end %>
          </ul>
       </div>
     </div>
     <!-----------tag search box------------>
     <!-----------post box------------>
       <div class="index-inner-area">
         <p font-size="20px">投稿する</p>
         <%@post.errors.full_messages.each do |message|%>
         <p class="errors"><%=message%></p>
         <%end%>
         <%= form_for @post, url: posts_path do |f| %>
           <%=f.text_area :content, class: "text-area", wrap:"hard", placeholder:"140文字以内です"%><br>
           <%= image_tag @post.postimage.url %><br>
           画像<br>
           <%= f.file_field :postimage, id: :users_img %><br>
           タグ<br>
           <%= text_field_tag 'post[tag_list]', @post.tag_list.join(','), placeholder:"カンマ区切りで複数タグになります" %><br><br>
           <%=f.submit value:"投稿", class:"button1"%>
         <%end%>
       </div>
   <!-----------post box------------>   
   <!-----------user-profile------------>
<div class="index-user">
  <div class="post-user-list-image">
    <%= image_tag  @current_user.img.url,:class => "user-image"%>
  </div>
    <div class="show-index">
      <%=link_to( "/users/#{@current_user.id}", class: "post-index-name") do%>
        <i class="far fa-user"><%=" "+@current_user.name%></i>
      <%end%>
    </div>
      <div class="follow-cover"> 
        <table class="follow-table">
          <tr>
            <td>投稿数</td>
            <td>フォロー</td>
            <td>フォロワー</td>
          </tr>
          <tr>
            <td><%=@current_user.posts.count%></td>
            <td><%=@current_user.follow_count%>人</td>
            <td><%=@current_user.followers_count%>人</td>
          </tr>
        </table>
      </div>
    </div>
             <!-----------user-profile------------>
             <!-----------search box------------>
    <div class="serch-main">
    <p font-size="15px">検索</p>
      <%= form_tag("/posts/search",:method => 'get') do %>
        <%= text_field_tag :search,"",:placeholder => "投稿内容を検索してください",class: "ser" %><br><br>
        <%= submit_tag 'Search', :name => nil ,class: "button1" %><br><br>
      <% end %>  
     </div>
              <!-----------search box------------>
     </div>
   </div>
   <!-----------post----------->
  <% @posts.each do |post|%>
    <div class="post-index-back">
      <div class="post-index-cover">
        <div class="post-main">
          <div class="post-main-box">
          <% if post.user.present? %>
            <div class="post-index-img-cover">
              <div class="post-index-img">
              <%= image_tag post.user.img.url, :class => "user-image" %>
              </div>
            </div>
              <div class="post-index-inner">
                <div class="post-main-detail">
                  <%=link_to(post.user.name, "/users/#{post.user.id}", class: "post-index-name")%>
                  <%= post.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[post.created_at.wday]})")  %>
                </div>
                  <div class="post-index-content"><%=simple_format(post.content)%></div>
                  <% if post.postimage.present? %>
         <!--画像--><%= image_tag post.postimage.url,:class => "post-image"%>
                  <%end%>
                  <div class="post-index-action">
                    <ul class="ultag">
                      <% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>
                        <%= link_to("/likes/#{post.id}/destroy",{method: "post",class:"tagf like-btn-unlike faa-pulse animated-hover"}, remote: true) do %>
                          <li><p class="itext"> <i class="fas fa-heart "></i></p></li>
                        <%end%>
                      <%else%>
                      <%= link_to("/likes/#{post.id}/create", {method: "post",class:"tagf like-btn faa-pulse animated-hover"},:select_id => "a") do %>
                        <li><p class="itext"> <i class="far fa-heart "></i></p></li>
                      <%end%>
                    <%end%>
                    <div class="tagf">   <li><p class="itext"><%= post.like_count %></li></p></div>  
                    <%=link_to(new_return_path(p_id: post.id),class:"tagf")do%>
                        <li><p class="itext"><i class="fas fa-reply"></i>返信</p></li>
                      <%end%>
                    <%if post.user_id==@current_user.id%>
                        <%=link_to("/posts/#{post.id}/edit",class:"tagf")do%>
                        <li><p class="itext">    <i class="fas fa-edit"></i>編集</p></li>
                      <%end%>
                      <%=link_to("/posts/#{post.id}/destroy",method: "post",data: {confirm: "本当に削除しますか？"},class:" tagf" ) do%>
                        <li><p class="itext"><i class="far fa-trash-alt"></i>削除</p></li>
                      <%end%>
                    <%end%>
                    <% post.tags.each do |tag| %> <!--タグサ--->
                      <li><%=link_to posts_index_path(:tagsearch =>  tag.name).gsub("+", "%20") do%>
                     <p class="itext"> <i class="fas fa-leaf"></i> <%=tag.name%></p></li>
                    <% end %> 
                    <% end %>
                    </ul>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
  
  <!---------------     返信     --------------------->
 
 <%unless post.returns == nil%>
 <div class="line-cover">
   <div class="line">
   </div>
 </div>
 <div class="return-index-back">
   <div class="post-index-cover">
     <div class="post-main">
       <div class="post-main-box">
 <%end%>
 <%@returns.each do |r|%> 
   <%if r.post_id == post.id%>
     <%if r.user.present?%>
       <div class="post-index-return-img-cover">
         <div class="post-index-return-cover-aug">
           <div class="post-index-return-img">
             <%= image_tag r.user.img.url, :class => "return-user-image" %>
         </div>
           <div class="post-index-return-name">
             <%=link_to(r.user.name, "/users/#{r.user.id}", class: "post-index-name")%><br>
             <%end%> 
          </div><br>
            <div class="post-index-return-content">
              <%=r.returncontent%>
            </div>
          </div>
            <%=link_to(edit_return_path(r.id),class:"return-edit")do%>
              <i class="fas fa-edit"></i>
            <%end%>
            <%=link_to("/returns/#{r.id}/destroy",method: "post",data: {confirm: "本当に削除しますか？",class:"return-edit"})do%>
              <i class="far fa-trash-alt"></i>
            <%end%>
           </div>
          <%end%>
        <%end%>
        </div>
     </div>
  </div>
  <div class="yohaku"></div>
   <!--------------------------------------------->
  <%end%>
  </div> 
</div>  

app/views/posts/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", story: @story  )) %>');

app/views/posts/new.html.erb
<div class="new-main">
  <div class="resister-area">
    <div class="inner-area">
      <p font-size="20px">投稿する</p>
        <%@posts.errors.full_messages.each do |message| %>
          <p class="errors"><%=message%></p>
        <%end%>
          <%= form_for @posts, url: posts_path do |f| %>
          <%=f.text_area :content, class: "text-area",  rows:"2", cols:"60", wrap:"hard", placeholder:"140字以内です"%><br>
          
          <p class="inp">画像</p>
          <%= image_tag @posts.postimage.url %><br>
          <%= f.file_field :postimage, id: :users_img %><br><br>
        
          <p class="inp">タグ</p>
          <%= text_field_tag 'post[tag_list]', @posts.tag_list.join(','),placeholder:"カンマ区切りで複数タグ" %><br><br>
          <%=f.submit value:"投稿", class:"button1"%>
          <%end%>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main">
  <div class="post-detail">
    <%= @posts.content %><br>
    <%= @posts.created_at %>
  </div>
    <% if Like.find_by(user_id: @current_user.id,post_id: @posts.id)%>
      <%= link_to("/likes/#{@posts.id}/destroy", {method: "post"},class:"post-detail") do %>
      <span class="fa fa-heart like-btn-unlike"></span>
    <%end%>
    <%else%>
      <%= link_to("/likes/#{@posts.id}/create", {method: "post"},class:"post-detail") do %>
      <span class="fa fa-heart like-btn"></span>
    <%end%>
    <%end%>
      <%= @likes_count %>
    <%if @posts.user_id==@current_user.id%>
      <%=link_to("編集","/posts/#{@posts.id}/edit",class:"post-detail")%>
      <%=link_to("削除","/posts/#{@posts.id}/destroy",{method: "post",class:"post-detail"})%>
    <%end%>
      <%=link_to(@users.name,"/users/#{@users.id}")%>
</div>

app/views/posts/unlike.js.erb
$("<%= @posts %>").html('<%= escape_javascript(render("posts/like")) %>');